### ISSUE TITLE
Does `useStateMachine` trigger re-renders when an update occurs in another component tree?

### ISSUE THREAD

**Issue by jfreedman-eagent** [bluebill1049/little-state-machine#110]
In my app, I want to use Little State Machine to share state between two separate component trees. However, when I tried to do so, one tree failed to update after an action was dispatched in the other. Is this expected behavior?

**Comment by bluebill1049** [comment]
not expected, can you share a simple codesandbox.

**Comment by jfreedman-eagent** [comment]
Here's the [Code Sandbox](https://codesandbox.io/s/romantic-browser-j7l08?file=/src/index.js). I might not have explained it super well. I have two separate `StateMachineProvider`s that I'd like to use the same state (in my actual app, it currently isn't feasible to combine them to use a single provider). With this setup, I expected both component trees to update at the same time, but only the tree where the update originated from was updated.

**Comment by bluebill1049** [comment]
Not possible with two providers at the moment.

**Comment by jfreedman-eagent** [comment]
Gotcha, just wanted to check if it was supported or not. Thanks for the quick response!

**Comment by bluebill1049** [comment]
np 👍
