### ISSUE TITLE
Code Sample in TS is not working correctly

### ISSUE THREAD

**Issue by tuppers360** [bluebill1049/little-state-machine#128]
When cloning the code sample from Code Sanbox (wild-dawn-ud8bq) you have to submit the form twice for the state to update?

Using:
`import { GlobalState } from 'little-state-machine';
export function updateFirstLastName(
  state: GlobalState,
  payload: {
    firstname: string;
    lastname: string;
  }
) {
  console.log('state before:', state);
  console.log('payload:', payload);
  return {
    ...state,
    yourDetails: {
      ...payload,
    },
  };
}`

and

`  const onSubmit = (data: FormValues) => {
    actions.updateFirstLastName(data);
    console.log('state after:', state);
  };`

this shows when changing any field it requires submission twice even when the payload is correct. I hope this is correct how I have gone about this.

**Comment by bluebill1049** [comment]
which codesandbox?

**Comment by tuppers360** [comment]
Sorry it is https://codesandbox.io/s/wild-dawn-ud8bq

**Comment by bluebill1049** [comment]
it's working fine for me. after click on submit and refresh the button and the data persist correctly.
