### ISSUE TITLE
Catching Storage error

### ISSUE THREAD

**Issue by jdozierezell** [bluebill1049/little-state-machine#132]
I'm receiving the following error when adding an image that exceeds the quota:

```Uncaught (in promise) DOMException: Failed to execute 'setItem' on 'Storage': Setting the value of '__LSM__' exceeded the quota.```

Is there a way to catch that error and do something with it? Right now I have a loading indicator that activates on click but the indicator is not deactivating on error because I haven't been able to figure out how to catch it.

**Comment by bluebill1049** [comment]
what are you trying to store in the session storage? there is a hard limit as far as i know.
