### ISSUE TITLE
TypeScript type definition are not fully accurate

### ISSUE THREAD

**Issue by kotarella1110** [bluebill1049/little-state-machine#14]
little-state-machine type are not fully accurate as follows:

<img width="400" src="https://user-images.githubusercontent.com/12913947/70023111-bbbc7c80-15d9-11ea-8ff4-e2528e4fb022.png">
<img width="400" alt="スクリーンショット 2019-12-03 14 05 22" src="https://user-images.githubusercontent.com/12913947/70024574-e577a280-15dd-11ea-839a-ab16e4c50e2d.png">

I think we need to improve DX as follows:

<img width="400" src="https://user-images.githubusercontent.com/12913947/70023178-e7d7fd80-15d9-11ea-8e7c-668a7170427c.png">

I want to create PR, but `useStateMachine` argument `updateStoreFunction` is difficult to support `undefined` or `{[key: string]: UpdateStoreFunction}` :cry:

My halfway results: https://github.com/kotarella1110/little-state-machine/commit/b061c771cb7fc2b246d9f290cd73cef9941be8f7

**Comment by bluebill1049** [comment]
you want to supply a codesandbox for this issue @kotarella1110 ?

**Comment by kotarella1110** [comment]
@bluebill1049 codesandbox is [here](https://codesandbox.io/s/little-state-machine-type-definition-are-not-fully-accurate-sgcwe?fontsize=14&hidenavigation=1&theme=dark)!

**Comment by bluebill1049** [comment]
```
type State = {
  key1: string;
  key2: string;
};

const { state } = useStateMachine<State>();
```

in terms of actions, I have just removed those errors.

it's kinda too complicated if you need to declare `Actions` types.
const { state } = useStateMachine<State, Actions>();
