### ISSUE TITLE
[Question] use with externalStore and get new state immediatley

### ISSUE THREAD

**Issue by svict4** [bluebill1049/little-state-machine#15]
I'm building a `react-hook-form` wizard and am trying to use the syncStores function.
When submitting a form to go to the next page, the entire state disappears, even if I'm just returning the existing sessionStorage.
Am I doing it right?

https://codesandbox.io/s/github/svict4/RHF-LSM-with-RR

It's probably because I don't know how to use the library properly, does anyone have a more concrete example of POSTing or GETing data from an endpoint for the transform function?

```jsx
function log(store: any) {
  console.log('this function logs the store:', store);
}

function PostData(store: any) {
  console.log('this function will trigger an API call to post data'); // is this the best place to put it?
}

window.sessionStorage.setItem(
  'formData',
  '{"yourDetails": {"firstname": "bull", "lastname": "le", "addresses": [{"street": "street"}]}}',
);

const mergeStore = (sessionData: any, data: any) => merge(data, sessionData);

// where externalStoreData is provided from an API
const externalStoreData = {
  yourDetails: { firstname: 'sdfsdf', middlename: 'dfsdfsdf' },
};

createStore(
  {
    yourDetails,
  },
  {
    name: 'formData',
    middleWares: [log, PostData],
    syncStores: {
      externalStoreName: 'API',
      transform: ({ externalStoreData, currentStoreData }) => {
        // just returning the current store doesn't seem to work after submit?
        return JSON.parse(window.sessionStorage.formData);
      },
    },
  },
);
```

Also, after setting the data in an action, I'd like to get state of the new store, so that I can pass it to my react-router function and do some logic. But `state` contains the previous state before updating, what's a better way of getting the new state?

```jsx
  const onSubit = data => {
    action(data);
    console.log(state); // I want to access the NEW state after the update
    props.history.push('./result'); // so I can use it here
  };
```

**Comment by bluebill1049** [comment]
hey @svict4 why are you using `syncStores`? are you sync external stores?

**Comment by svict4** [comment]
Heya I'm syncing to an external API (think Firebase/MongoDB store).
(for now I'm just mocking it with below) 

```jsx
// where externalStoreData is provided from an API
const externalStoreData = {
  yourDetails: { firstname: 'randomSTuffFromAPI', middlename: 'stuffFromAPI' },
};
```

I'm submitting it to the API every time the store edited. So does this mean I have to connect it in `middlewares`?

Let's say I'm going to a step in the wizard which has existing data. What hook do I need to call to populate/merge my store? Do I populate `sessionStorage` directly and little-state-machine does the rest, or do I have to populate `externalStoreData`?

Than... (and this is a question for the RHF spectrum)
I imagine I would [`reset`](https://react-hook-form.com/api/#reset) my form so my form would have the new values? or could i use `useForm({  defaultValues: {} })`

Thanks for awesome the libraries 👍

**Comment by bluebill1049** [comment]
hey @svict4 sync external store only happen once, which is when you app landed. for each action you may need to use `middleware`. I haven't fully use `middleware` in our project at work just yet. feel free to try it and let me know if there is issue around it, i will try to patch it ASAP.

**Comment by bluebill1049** [comment]
> I imagine I would [`reset`](https://react-hook-form.com/api/#reset) my form so my form would have the new values? or could i use `useForm({ defaultValues: {} })`

you should be able to use `reset()` or `reset({})`.

**Comment by svict4** [comment]
> sync external store only happen once

Ah okay, I thought it was each time.
I'll give it a try. If I have success, I'll create a template/demo project for others to use.

**Comment by bluebill1049** [comment]
yea if each time invoke would be too expensive for your app to run. but let me know how did you go with the middleware.

**Comment by svict4** [comment]
Hmm looks the state gets deleted when you hook up a middleWares

```jsx
function log(store) {
  console.log(store);
}

createStore(
  { someObject },
  { 
    middleWares: [log] 
  }
);
```
where my action is simply
```jsx
export default function updateAction(state, payload) {
  return {
    data: {
      ...state.data,
      ...payload
    }
  };
}
```

Debug shows that the state gets updated with the correct action name and `window.STATE_MACHINE_GET_STORE` returns the JSON correctly.

**Comment by svict4** [comment]
![LSM-middlewares](https://user-images.githubusercontent.com/1137112/70106094-79a14280-168e-11ea-9735-792ac01073a3.gif)
@bluebill1049 any clues why the store disappears/devtools doesn't show the store?

**Comment by bluebill1049** [comment]
can you share some of your code?

**Comment by bluebill1049** [comment]
and your action?

**Comment by svict4** [comment]
Hey @bluebill1049 just circling back to this.
If we use the basic example of console logging the store as a middleware (as given in the docs)
https://codesandbox.io/s/little-state-machine-demo-zc30h

Are our functions meant to be returning back the `globalState`? The callback https://github.com/bluebill1049/little-state-machine/blob/master/src/stateMachine.tsx#L130 is returning `undefined` back to `updateStore`

Any clues? 😊

**Comment by bluebill1049** [comment]
hey @svict4 that's the part that i want to fix (currently at my work we have similar issue) we shouldn't have to return `GlobaState`,  but right now you have to... until i fix it. you can report an issue on it, i will sort it out over the weekend 👍

**Comment by erwagasore** [comment]
@bluebill1049 this is the same issue I am facing right  now. Any idea on how it  was solved?
Thank you


![LSM-middlewares](https://user-images.githubusercontent.com/1137112/70106094-79a14280-168e-11ea-9735-792ac01073a3.gif)
@bluebill1049 any clues why the store disappears/devtools doesn't show the store?

_Originally posted by @svict4 in https://github.com/bluebill1049/little-state-machine/issues/15#issuecomment-561442425_
