### ISSUE TITLE
Using with node

### ISSUE THREAD

**Issue by schrapel** [bluebill1049/little-state-machine#16]
Hey, Thanks for the great package. I am trying to use this with Next.js but I get the following error when SSR is happening. Would you consider adding support for isomorphic apps in the future.

```
ReferenceError: window is not defined
createStore
./node_modules/little-state-machine/dist/index.js:164:9
```

**Comment by bluebill1049** [comment]
hey @schrapel i will patch that soon 👍

**Comment by bluebill1049** [comment]
hey @schrapel can you give me a screenshot of the line which cause this issue?

**Comment by bluebill1049** [comment]
a codesandbox with SSR will be even nicer.

**Comment by schrapel** [comment]
Sorry for the late reply. I will try get that to you in a couple of days. I am a little busy with other things

**Comment by bluebill1049** [comment]
screenshot of the actual code line would be great

**Comment by schrapel** [comment]
![Screenshot 2019-12-12 at 15 47 52](https://user-images.githubusercontent.com/3613405/70747848-d8059b00-1cf6-11ea-9b10-1aec0533f3b1.png)

Although I guess the error makes sense as it's trying to use local storage. It would be nice if it would wait until the client renders to trigger.

**Comment by bluebill1049** [comment]
yea I will try it out with a next.js app this weekend. thanks for the screenshot

**Comment by bluebill1049** [comment]
FYI: i haven't forget about it. I am working on RHF next major version. so i am bit busy i will come back to it tho.

**Comment by schrapel** [comment]
There is no sense of urgency from me. I appreciate your update
