### ISSUE TITLE
[Bug] middleWares option expects state

### ISSUE THREAD

**Issue by svict4** [bluebill1049/little-state-machine#19]
`CreateStore`'s `middleWares` option expects `globalState` to be returned, or undefined will be returned to the [`updateStore` function](https://github.com/bluebill1049/little-state-machine/blob/master/src/stateMachine.tsx#L130) and will error.
https://codesandbox.io/s/little-state-machine-demo-zc30h

Thus, the super simple example in the readme does not work.

Expected: if nothing is returned from any `middleWares` callback, that it retains the previous `globalState`.

**Comment by bluebill1049** [comment]
Thanks buddy :) I will take a look this one soon.
