### ISSUE TITLE
How do you delete an item from the store?

### ISSUE THREAD

**Issue by KevinKelbie** [bluebill1049/little-state-machine#20]

**Comment by bluebill1049** [comment]
hey @KevinKelbie can you give more detail on the question (codesandbox)? or consider asking question at our spectrum channel.

**Comment by bluebill1049** [comment]
it's all JS function and return values :)

**Comment by KevinKelbie** [comment]
thanks, I ended up coming up with a solution which seems to work fine but maybe your solution is better.

```
action({items: state.items.filter((item) => {
    return condition
})})
```
