### ISSUE TITLE
Enable React-Native support

### ISSUE THREAD

**Issue by enormousrodent** [bluebill1049/little-state-machine#23]
When trying to use your awesome state machine in my React native app i get the error: 

Can't find variable: document.

I assume this is the DEV tools causing this problem.  Any clues you can give me or timeline for implementation would be awesome

Thanks

**Comment by bluebill1049** [comment]
Will fix it over the weekend, should be easier fix :)

**Comment by enormousrodent** [comment]
Thanks @bluebill1049  - I think its the development tool that is causing the issue!

**Comment by DarkSouls101** [comment]
Don’t use the developer tool for RN is not supported :)

Cheers
Bill

**Comment by enormousrodent** [comment]
I didn't even install it and the error happened.  The error was just after doing the import into a file.

**Comment by bluebill1049** [comment]
hey @enormousrodent are you sure it's not caused by importing DevTool, because the code is only live in dev tool. can you send a screenshot of the error and how you import the lib?

**Comment by bluebill1049** [comment]
<img width="851" alt="Screen Shot 2020-02-23 at 7 35 19 pm" src="https://user-images.githubusercontent.com/10513364/75106742-a8b6c700-5673-11ea-9a10-c1b52309eab8.png">

**Comment by LucidNinja** [comment]
Hey @bluebill1049 - I'm having this same issue! I didn't realise this was your repo too! I am trying to implement your [example](https://codesandbox.io/s/form-wizard-pages-kkg7m) in React Native. Has there been an update for this?

**Comment by LucidNinja** [comment]
<img width="393" alt="Screen Shot 2020-03-17 at 3 12 34 pm" src="https://user-images.githubusercontent.com/29149363/76822690-bd950d80-6861-11ea-9b78-d482b8ca3d23.png">

**Comment by bluebill1049** [comment]
hmmm strange i will test it out tonight as well. should be a simple fix.

**Comment by LucidNinja** [comment]
@enormousrodent did you find a fix or workaround?

**Comment by bluebill1049** [comment]
@LucidNinja is anyway you can step into which line cause this issue?

**Comment by bluebill1049** [comment]
not a bug :) just dont import the DevTool

`import { StateMachineProvider, createStore } from 'little-state-machine'`

**Comment by LucidNinja** [comment]
Sorry I'm trying to debug, so I haven't found the line causing the issue - I'm not importing DevTool anywhere that I can see? I literally just pasted your code `import { StateMachineProvider, createStore } from 'little-state-machine'` into my file and I get the error?

**Comment by LucidNinja** [comment]
Where would I be importing DevTool?

**Comment by LucidNinja** [comment]
Does your stateMachine.tsx not import devtools https://github.com/bluebill1049/little-state-machine/blob/master/src/stateMachine.tsx ? Sorry I'm not heaps familiar with tsx.

**Comment by bluebill1049** [comment]
i just did a build myself and it's working without the DevTool.

**Comment by LucidNinja** [comment]
Ok great! Is there documentation on how to do that? Sorry I'm on a collaborative project - how do I disable the DevTool? Is it a manual import somewhere?

**Comment by LucidNinja** [comment]
I did a search through the app folder and couldn't see DevTool anywhere?

**Comment by bluebill1049** [comment]
oh shit it is breaking the app...

**Comment by bluebill1049** [comment]
let me take a look tonight.

**Comment by LucidNinja** [comment]
No worries mate! Thank you! I thought I was going insane haha

**Comment by LucidNinja** [comment]
Hey @bluebill1049  -  can you confirm is this has propagated to NPM, and if so, what version it is? I'm still having issues, but could be because of a version issue.

**Comment by bluebill1049** [comment]
hey @LucidNinja 2.12.0?

**Comment by LucidNinja** [comment]
<img width="364" alt="Screen Shot 2020-03-17 at 6 54 20 pm" src="https://user-images.githubusercontent.com/29149363/76836420-b7625980-6880-11ea-81ef-ca443f8c61a6.png">
I'm using v 2.12.0 and now receiving this error.

`undefined is not an object (evaluating 'storageTyle.getItem')`

**Comment by bluebill1049** [comment]
![Screen Shot 2020-03-17 at 7 25 44 pm](https://user-images.githubusercontent.com/10513364/76836556-1f1aa380-6885-11ea-8143-fa9bfb3c730d.png)

Take a look release note: https://github.com/bluebill1049/little-state-machine/releases/tag/v2.12.0

react native doesn't have sessionStorage, use `AsyncStorage`

**Comment by LucidNinja** [comment]
BEAUTIFUL! Works perfectly. You're amazing. Thanks so much!
