### ISSUE TITLE
Way to turn off storage by default

### ISSUE THREAD

**Issue by devoNOTbevo** [bluebill1049/little-state-machine#28]
I was using `little-state-machine` with `react-hook-form` and had some conditional state that I didn't want lsm to remember on load.

The only way I found to implement this was something like this:

```javascript
const initialState = {/* whatever you want */}
createStore(
  { ...initialState },
  {
    middleWares: [],
    syncStores: {
      // you can sync with external store and transform the data
      externalStoreName: 'initial',
      transform: ({ externalStoreData, currentStoreData }) => {
        return {
          ...initialState,
         // here add any other state from external or current
        };
      }
    }
  }
);
```

I actually really like this package a lot and would be happy submitting a PR for what I'm thinking, unless I'm not on the right track.

**Comment by bluebill1049** [comment]
hey @devoNOTbevo thanks for the support :) keep it simple. Maybe we should create a folder for examples and doing it just like RHF (code + CSB)? your thoughts?

**Comment by devoNOTbevo** [comment]
@bluebill1049  yes, I think that could be helpful.  I liked that about RHF actually - great job on that site.  One question - is it possible to prevent LSM from storing at all?  This is developer's responsibility, but I am concerned about instances where user has not given consent to storage, when it's necessary.  

In my example, LSM is still storing the data, I'm just not using all of it.

**Comment by bluebill1049** [comment]
oh you probably can use `setStorageType` and give it an object with session storage alike API.

call `setStorageType({ setItme: () => {}, ...})` before `createStore`

**Comment by devoNOTbevo** [comment]
@bluebill1049  I will give that a try on a current project and report back.  These might can be examples to give also, like you suggested.

**Comment by bluebill1049** [comment]
if i have some extra time, i will do a codesandbox for you @devoNOTbevo :)

**Comment by devoNOTbevo** [comment]
I was able to by setting both `getItem` and `setItem`:

```typescript
setStorageType({
    setItem: () => {},
    getItem: () => {
        return createInitState();
    },
    ...localStorage
});
createStore({ ...createInitState() });
```
