### ISSUE TITLE
Exported type for action expects store.

### ISSUE THREAD

**Issue by devoNOTbevo** [bluebill1049/little-state-machine#30]
The type that is exported from useStateMachine is `Action`

```typescript
export function useStateMachine<T extends Store = Store>(
  updateStoreFunction?: UpdateStore,
  options?: Options,
): {
  action: Action;
  actions: Actions;
  state: T;
} {
```

which reflects this type:

```typescript
export declare type Action = (store: any, payload: any) => any;
export declare type Actions = {
    [key: string]: Action;
};
```

which means that when you use the function `action` or functions from the `actions` object, it expects both parameters.

#### Proposal

change return types to `UpdateStoreFunction`:
```typescript
export declare type UpdateStoreFunction = <T>(payload: T) => T;
```

in order to reflect usage per documentation.

**Comment by devoNOTbevo** [comment]
Just saw [this issue that is similar](https://github.com/bluebill1049/little-state-machine/issues/14#issuecomment-562920164) - were these not implemented?

**Comment by bluebill1049** [comment]
Yeah to be honest, i didn't give too much love on the Type with this lib. I will come to it.

**Comment by devoNOTbevo** [comment]
@bluebill1049 don't worry - and I have a few other items I may address as well.  Not intended to be a burden: anything I bring up, I try to bring a solution for and can submit PR if you're open to it.

**Comment by bluebill1049** [comment]
oh yeah @devoNOTbevo 100%. thanks ❤️

**Comment by bluebill1049** [comment]
actually all those action only return `void`
