### ISSUE TITLE
Unexpected Reset Behavior

### ISSUE THREAD

**Issue by rothnic** [bluebill1049/little-state-machine#32]
This might be a misunderstanding on my part, but this at least seems unexpected. I can't seem to get a working example where I reset the state of the form to where it started without refreshing the page manually.

I tried both calling the `window.STATE_MACHINE_RESET` and creating a reset function that sets the state back to what the app started with. Neither of these seem to trigger the app to reload. Additionally, the DevTool reset button doesn't seem to actually reset the data in the DevTool without refreshing the window, which seems a bit odd to have a button that doesn't show any feedback.

Here is my [modified demo app](https://codesandbox.io/s/little-state-machine-demo-6rlr9?file=/src/index.js) with the reset function. I added a reset button that triggers the reset function, which just sets the state back to the original.

Steps I'm taking in my demo app:
* Show console
* Change "bill" to "tom"
* Click Submit (see console where data has been updated)
* Click Reset (see console where data has been updated)
* Observe the first field still says "tom"

Also:
* Show DevTool
* Change "bill" to "tom"
* Click "Reset" in the DevTool
* Observe no change in the data
* Click the refresh button for the app window
* Observe first input now says "bill"

**Comment by bluebill1049** [comment]
Yea the reset will need a restart, honestly, i haven't spent too much time with the dev tool.

**Comment by rothnic** [comment]
> Yea the reset will need a restart, honestly, i haven't spent too much time with the dev tool.

I wasn't really worried about the devtool, but was worth mentioning. If you look at the modified demo though, should setting the state back to the original not cause the app to re render? Instead of using `window.STATE_MACHINE_RESET`, I'm actually updating the state. The console debug output shows that the state has been changed, but the app doesn't update.

**Comment by bluebill1049** [comment]
That's due to RHF is uncontrolled and you need to use its reset function: https://codesandbox.io/s/little-state-machine-demo-rkb2q?file=/src/form.js

**Comment by rothnic** [comment]
Thanks a bunch. I hadn't come across the reset topic in RHF. That was what I needed.
