### ISSUE TITLE
TypeError `state is undefined` 

### ISSUE THREAD

**Issue by devoNOTbevo** [bluebill1049/little-state-machine#35]
I've tried to investigate using the transpiled code, but even the code sandbox is broken for `react-hook-form`.  Hoping to see what the issue was, but have to move forward on a project.

https://codesandbox.io/s/form-wizard-pages-kkg7m

I also saw that this `useContext` is where it's using the state:

<img width="607" alt="image" src="https://user-images.githubusercontent.com/15235244/80160324-fa57d100-8592-11ea-98ea-1fab26831f38.png">

**Comment by bluebill1049** [comment]
I will look into this.

**Comment by bluebill1049** [comment]
hmmm something is broken.

**Comment by bluebill1049** [comment]
looks like it's the latest version break the lib.

**Comment by bluebill1049** [comment]
fixed and published.
