### ISSUE TITLE
Still includes react-json-view when not using DevTools

### ISSUE THREAD

**Issue by ururk** [bluebill1049/little-state-machine#36]
I've noticed, even when building without `<DevTools />`, `react-json-view` is still bundled in the application. Perhaps this is intentional, but seems unnecessary. When bundled it takes up about 149KB uncompressed.

**Comment by bluebill1049** [comment]
hey @ururk what's the bundle tool that you are using? definitely not intentional.

**Comment by ururk** [comment]
create-react-app - not ejected

**Comment by bluebill1049** [comment]
may i know which version?

**Comment by ururk** [comment]
3.4.1

**Comment by ururk** [comment]
I'm not sure it's create-react app's fault - in the dist folder for little-state-machine, index.js, line 425-429:

```js
const clone = require('lodash.clonedeep');
let ReactJson = (props) => React.createElement("div", Object.assign({}, props));
if (typeof window !== 'undefined' && typeof document !== 'undefined') {
    ReactJson = require('react-json-view').default;
}
```

I'm not as well-versed on the build/bundling side of things, but it looks to me like require will always be called when run in-browser.

**Comment by bluebill1049** [comment]
looks like that's a bug at little state machine.

**Comment by ururk** [comment]
Yep - sorry if I wasn't clear enough!

**Comment by bluebill1049** [comment]
nah all good, i think the reason little state machine did that because of SSR: https://github.com/mac-s-g/react-json-view/issues/121

**Comment by bluebill1049** [comment]
i may have to switch to another lib...

**Comment by bluebill1049** [comment]
can you try this version: `3.0.0-beta.1`

**Comment by ururk** [comment]
Trying it out - need to do a few tests.

**Comment by bluebill1049** [comment]
core codebase is not changed @ururk only that dev tool with json view.

**Comment by ururk** [comment]
I know - just wanted to try running it locally to see the new tree view, and build my app to see if it included the new library (`react-json-tree`). 

It now includes the new library, although it is smaller in size.

**Comment by bluebill1049** [comment]
sounds good to me :) so it's still in the prod build? 🤔

**Comment by ururk** [comment]
Yes - still in prod build. I even tried removing the import dev and `{process.env.NODE_ENV !== 'production' && <DevTool />}`.

**Comment by bluebill1049** [comment]
can i see a snapshot of the build result?

**Comment by ururk** [comment]
<img width="1267" alt="image" src="https://user-images.githubusercontent.com/137989/80441203-69596080-88d8-11ea-98ae-94ff3337acbe.png">

**Comment by bluebill1049** [comment]
looks like this one is CRA related? https://github.com/facebook/create-react-app/issues/2748

**Comment by bluebill1049** [comment]
Here is the `index.ts` file

```
import {
  setStorageType,
  createStore,
  StateMachineProvider,
  useStateMachine,
} from './stateMachine';
import { DevTool } from './components/DevTool';
import StateMachineContext from './StateMachineContext';

export {
  setStorageType,
  createStore,
  StateMachineProvider,
  useStateMachine,
  StateMachineContext,
  DevTool,
};
```

**Comment by ururk** [comment]
It looks likely to be a CRA/webpack config issue.

I'm not sure if this helps, but at the top of the beta `dist/index.js` file for little-state-machine, it gets included like so:

```js
var React = require('react');
var JSONTree = _interopDefault(require('react-json-tree'));
var reactSimpleAnimate = require('react-simple-animate');
```

I removed the reference to `JSONTree` inside of `DevToolStateTree`, and it still included the library, so at this point CRA/webpack must not be detecting that `JSONTree` is never referenced.

**Comment by bluebill1049** [comment]
Thanks for helping @ururk 

i have sent a StackOverflow question around this as well: https://stackoverflow.com/questions/61471907/export-module-with-node-env-with-ts

**Comment by ururk** [comment]
Thanks! FYI - it is using `index.es.js` - not `index.js` from the dist folder. 

I did a quick test and commented out the `createElement` calls in `DevToolStateTree` and it still included `react-json-tree`, so this feels like a webpack/CRA bug like you suspected.

**Comment by bluebill1049** [comment]
Yea, and it's difficult with TS as well, it probably doesn't support dynamic export. I will publish v3 anyhow later tonight, it's better than what we got right.

**Comment by ururk** [comment]
Yep! With the new library, I noticed you cannot scroll the tree when it is expanded past the browser window, can't recall now what the old behavior was, and if it is my app or not :P

**Comment by bluebill1049** [comment]
@ururk i will fix that :)

**Comment by D1plo1d** [comment]
I'm also seeing react-hook-form in my parcel 2 builds. Am I right in understanding that this is fixed on the master branch? Also little-state-machine is showing as 16.01KB?

```
$ NODE_ENV=production parcel build src/index.html --experimental-scope-hoisting --detailed-report 20
✨  Built in 6.62s.

dist/src.eb090cc8.js                                             545.78 KB    6.54s
├── node_modules/react-json-view/dist/main.js                    147.96 KB     11ms
├── node_modules/react-hook-form/dist/react-hook-form.es.js        33.8 KB     71ms
├── node_modules/jss/dist/jss.esm.js                              25.36 KB     23ms
├── node_modules/little-state-machine/dist/index.es.js            16.01 KB      5ms
```

**Comment by bluebill1049** [comment]
I think i know the fix now, i will sort out in the next couple days.

**Comment by bluebill1049** [comment]
i will have to move dev tool out from the main repo.
