### ISSUE TITLE
Does it work with IE 11 ?

### ISSUE THREAD

**Issue by erickbelfy** [bluebill1049/little-state-machine#40]
Recently i tried to make it work with old browsers but i couldn't make it.

**Comment by bluebill1049** [comment]
I think you will need polyfills, can you share the error log?

**Comment by erickbelfy** [comment]
Indeed, IE11 doens't have support for [Object.entries()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/entries) it is possible to add some documentation section regarding polyfills? Unfortunatelly the product that i am working on has support for IE 11 :( .

**Comment by bluebill1049** [comment]
```
if (!Object.entries) {
  Object.entries = function( obj ){
    var ownProps = Object.keys( obj ),
        i = ownProps.length,
        resArray = new Array(i); // preallocate the Array
    while (i--)
      resArray[i] = [ownProps[i], obj[ownProps[i]]];
    
    return resArray;
  };
}
```

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/entries

can you try if this fix the issue?

**Comment by erickbelfy** [comment]
absolutelly, is there some guidelines for me to test and provide PR's in the project?

**Comment by bluebill1049** [comment]
We use at the work, but we have all the polyfill for shitty IE11. perhaps we can have a new section under Readme info about some of the polyfill that you will need.

**Comment by erickbelfy** [comment]
I will do a quick smoke test here with the polyfill just to confirm that it is working properly, i will add the docs after that.

**Comment by bluebill1049** [comment]
Thanks @erickbelfy

**Comment by erickbelfy** [comment]
Something that i noticed is that the package is compressed as es. I guess that is not IE11 compatible, look:

```
[WDS] Disconnected!
Possible Unhandled Promise Rejection: SyntaxError: Syntax error
   "Possible Unhandled Promise Rejection:"
   {
      [functions]: ,
      __proto__: { },
      description: "Syntax error",
      message: "Syntax error",
      name: "SyntaxError",
      number: -2146827286,
      stack: "SyntaxError: Syntax error
   at ./node_modules/little-state-machine/dist/index.es.js (http://10.25.254.218:4002/dist/client.vendors~app.part.js:73139:1)
   at __webpack_require__ (http://10.25.254.218:4002/dist/client.js:64:12)
   at eval code (eval code:6:22)
   at ./src/components/Reassign/index.js (http://10.25.254.218:4002/dist/client.app.part.js:3460:1)
   at __webpack_require__ (http://10.25.254.218:4002/dist/client.js:64:12)
   at eval code (eval code:22:22)
   at ./src/components/App/App.js (http://10.25.254.218:4002/dist/client.app.part.js:391:1)
   at __webpack_require__ (http://10.25.254.218:4002/dist/client.js:64:12)
   at eval code (eval code:19:22)
   at ./src/components/App/AppContext.js 
```

**Comment by bluebill1049** [comment]
hmmm may have to build an IE version, just like RHF...

**Comment by erickbelfy** [comment]
I am providing some changes in the tsconfig.json file, i will push a PR so we can review it together.

**Comment by bluebill1049** [comment]
you want to take a look RHF? we can have ie 11 config, so it doesn't impact those users who do not support IE 11.

**Comment by erickbelfy** [comment]
sure, i will take a look and see the implementation done there

**Comment by erickbelfy** [comment]
#41 this PR provides support for IE11

**Comment by erickbelfy** [comment]
I don't know how to tag a PR properly hahaha, so sorry.

**Comment by erickbelfy** [comment]
The above PR should handle the configuration files also the documetation for browser compatibility, let me know what do you think

**Comment by bluebill1049** [comment]
awesome! thanks heaps @erickbelfy will get a beta version tonight.

**Comment by erickbelfy** [comment]
Glad to help the project!

**Comment by bluebill1049** [comment]
can you please test out this version: `little-state-machine@3.1.0-beta.1`?

**Comment by erickbelfy** [comment]
The version is not available, at least for me look:

<img width="659" alt="Screen Shot 2020-05-26 at 7 56 51 AM" src="https://user-images.githubusercontent.com/1584725/82898009-8ceae780-9f26-11ea-89ab-390a8fcf213f.png">

**Comment by bluebill1049** [comment]
try again, it should be there now: https://bundlephobia.com/result?p=little-state-machine@3.1.0-beta.1

**Comment by erickbelfy** [comment]
I tested here and i noticed that if i import something like 
`import {createStore} from 'little-state-management' ` it says that *Casing of little-state-machine does not match the underlying filesystem.*

**Comment by bluebill1049** [comment]
works here: https://codesandbox.io/s/lrz5wloklm

**Comment by erickbelfy** [comment]
Perfect, if it works in code sandbox, i probably miss something locally. i guess ti's all good!

**Comment by bluebill1049** [comment]
can you please do a double-check with IE11? I don't have a PC at home otherwise i would:

`import {createStore} from 'little-state-management/dist/little-state-machine.ie11'`

**Comment by erickbelfy** [comment]
it seems to be working here: https://codesandbox.io/s/bold-glade-kprj6?file=/src/App.js

**Comment by bluebill1049** [comment]
oh cool as long as it worked on IE11 we are good to go! closing now will publish it tmr morning.
