### ISSUE TITLE
AsyncStorage doesn't work with react-native

### ISSUE THREAD

**Issue by happyfloat** [bluebill1049/little-state-machine#48]
I don't see how this should currently work, since AsyncStorage is async.... ?

At least I don't know how to make it work in my App. It doesn't restore / or save the data.

Any hints would be helpful. Thank you ❤️ 

```jsx
import React from 'react';
import AsyncStorage from '@react-native-community/async-storage';
import {
  StateMachineProvider,
  createStore,
  setStorageType,
} from 'little-state-machine';

import App from './App';

setStorageType(AsyncStorage);

const data: LittleState = {
  xFormData: {},
};

createStore(data);

const AppContainer = () => (
    <StateMachineProvider>
        <App />
    </StateMachineProvider>
);

export default AppContainer;
```

**Comment by bluebill1049** [comment]
hey take a look this issue: https://github.com/bluebill1049/little-state-machine/issues/23

**Comment by bluebill1049** [comment]
https://github.com/bluebill1049/little-state-machine/releases/tag/v2.12.0

**Comment by happyfloat** [comment]
Thanks, I already looked into that. It's not working like that. My formData works fine in the form, it's just not persisted or restored correctly. How do you handle the async nature of the AsyncStorage in your code?

**Comment by bluebill1049** [comment]
if data arrived async, just use `reset` API at useEffect to reset the form with defaultValues.

**Comment by happyfloat** [comment]
The state is always empty after I refresh the App.

**Comment by happyfloat** [comment]
Is this the correct place in your code, where the data should be retrieved from the store?
https://github.com/bluebill1049/little-state-machine/blob/33fd69eb6a37f3c37d5d097e09d163616be2f613/src/logic/getBrowserStoreData.ts

If yes, it can not work, because it is not asynchronous. `getItem` will return a promise.

**Comment by bluebill1049** [comment]
> Is this the correct place in your code, where the data should be retrieved from the store?
> https://github.com/bluebill1049/little-state-machine/blob/33fd69eb6a37f3c37d5d097e09d163616be2f613/src/logic/getBrowserStoreData.ts
> 
> If yes, it can not work, because it is not asynchronous. `getItem` will return a promise.

you want to send a PR just turn it into a async await?

**Comment by happyfloat** [comment]
I don't think it's as easy as that. We would need to refactor almost everything to make it asynchronously? It would also be a breaking change, not sure if it fits this library then :/.

Guess I need to switch back to redux for now. Thanks for your quick reply!

**Comment by bluebill1049** [comment]
can you provide more detail? actually i will give this a try with RN this weekend, last time another user confirmed its working so i moved on, you can move on with redux, i will sort out to make sure this work for RN, this should be very simple task.

**Comment by happyfloat** [comment]
I can not just make this one function async? This functions is also used in other places, which all would need to await the result of it then, which itself would require it to be async. Unfortunately I didn't see an easy way out here.

**Comment by bluebill1049** [comment]
That's fine, pretty easy stuff, I will sort out over the weekend: https://reactnative.dev/docs/asyncstorage.html

**Comment by bluebill1049** [comment]
`little-state-machine@3.1.0-beta.2`

**Comment by happyfloat** [comment]
Wow, that was quick... I couldn't count on that. I already switched my green-field project to React's new [recoil library](https://recoiljs.org/). But the react-native support is also not really there yet (only with a patch)... I will see how it is going and if necessary switch back again. 

The react world is moving way to fast... for my API cache/state I'm going with [react-query](https://react-query.tanstack.com/) anyway.

Anyway, I will try your change later today to give you feedback if it works on my side! Thank you very much. 👍

**Comment by bluebill1049** [comment]
sound good to me! thanks.

**Comment by happyfloat** [comment]
Was not able to do it today, but I will definitely try it on Monday then, sorry for that!

**Comment by bluebill1049** [comment]
no worries at all, thanks for helping. Just want to make sure it will work for others before the merge and publish it.

**Comment by happyfloat** [comment]
It works very well now 👍

**Comment by bluebill1049** [comment]
oh cool! thanks for the testing.
