### ISSUE TITLE
how to use persist state in react-native

### ISSUE THREAD

**Issue by kenphil** [bluebill1049/little-state-machine#53]
import AsyncStorage from '@react-native-community/async-storage'
import {StateMachineProvider, createStore, setStorageType} from 'little-state-machine'

setStorageType(AsyncStorage)
createStore(InitStore, {name: 'xxx'})

const App = () => {
  return (
    <StateMachineProvider>
        ...
    </StateMachineProvider>
  )
}

is this correct?
when i shake & reload the app, the store's gone

**Comment by bluebill1049** [comment]
I have removed React Native for now, until I have a good solution for this.It's achievable but i need to build another path for async store read because async-storage is async.
