### ISSUE TITLE
No documentation on how to "reset" via window.STATE_MACHINE_RESET in production outside dev tools / environment

### ISSUE THREAD

**Issue by VinLucero** [bluebill1049/little-state-machine#56]
Could you please describe how to achieve the "reset" / window.STATE_MACHINE_RESET functionality upon form completion in production?

I would like to allow a new user to fill out the registration form after another user has already completed it.

**Comment by bluebill1049** [comment]
you should create an `action` and return your empty state.

**Comment by VinLucero** [comment]
Do you by chance have an example of this?

I can’t seem to find any on GitHub or Stackoverflow.

Thanks!

**Comment by ilicmarko** [comment]
As Bill said. Inside an action, let's call it reset return an empty object `{}`.

```js
// action.js
export function resetState() {
  return initialState
}

// component.js
const { state, action } = useStateMachine(resetState)

// Call reset
action({})
```

Because of TypeScript you must pass something. Calling `action()` will not pass TS lint, but if you don't use TS you can do it.

**Comment by bluebill1049** [comment]
> As Bill said. Inside an action, let's call it reset return an empty object `{}`.
> 
> ```js
> // action.js
> export function resetState() {
>   return initialState
> }
> 
> // component.js
> const { state, action } = useStateMachine(resetState)
> 
> // Call reset
> action({})
> ```
> 
> Because of TypeScript you must pass something. Calling `action()` will not pass TS lint, but if you don't use TS you can do it.

Thanks @ilicmarko for helping ❤️
