### ISSUE TITLE
using multiple actions

### ISSUE THREAD

**Issue by svict4** [bluebill1049/little-state-machine#59]
Hey dumb question as I seemingly can't read the type properly

if I set up multiple actions like so:

```javascript
const { state, actions } = useStateMachine(
    { saveAction, sorryAction },
    { saveAction: "saveToDB", sorryAction: "sorry" }
);
```

how do I send an update to only one of the actions? it's not this:

```javascript
actions([{ key: "sorry" }], {
    reason: "you dun goofed"
});
```

**Comment by bluebill1049** [comment]
hey @svict4, is this what you after?

```
const { actions } = useStateMachine({
  action1,
  action2,
});

actions.action1()
```

**Comment by svict4** [comment]
Thank you. Am a certified idiot :)

**Comment by bluebill1049** [comment]
> Thank you. Am a certified idiot :)

nah, you are not ❤️ wondering if you have received my stickers?

**Comment by svict4** [comment]
Oh yes I have! Will post a pic to Twitter 🙏

**Comment by bluebill1049** [comment]
> Oh yes I have! Will post a pic to Twitter 🙏

You don't have to post on twitter, I am just double check if you receive them. (happy to send again if not received) ❤️
