### ISSUE TITLE
Async action support [Question]

### ISSUE THREAD

**Issue by ssuvorov** [bluebill1049/little-state-machine#62]
Hey,
If I replace the action here https://codesandbox.io/s/wild-dawn-ud8bq?file=/src/yourDetailsAction.ts
with an async fn it doesn't work. Async is not supported, right? Any plans for future releases?
e.g.
```js
export async function updateFirstLastName(state, payload) {
  return Promise.resolve({
    ...state,
    ...payload
  });
}
```

**Comment by bluebill1049** [comment]
I will try to get it to work under V4. 👍 still under construction.

**Comment by bluebill1049** [comment]
hey, @ssuvorov did some quick investigation, I think it's easier to keep async function as a wrapper and update state syn.
