### ISSUE TITLE
Way to use this with multiple stores and type safety

### ISSUE THREAD

**Issue by pitops** [bluebill1049/little-state-machine#67]
Is there any way to create multiple stores while ensuring state type safety?

As far as I see you need to define a global definition file that corresponds to globalstate but i want to have several small stores instead.

PS: Thanks for creating this

**Comment by bluebill1049** [comment]
at the moment, we only support a single store. 👍

**Comment by rpk-red** [comment]
@bluebill1049 is this still the case regarding multiple stores?
