### ISSUE TITLE
Can't use it on react native

### ISSUE THREAD

**Issue by jvalle-traxion** [bluebill1049/little-state-machine#69]
I've been trying to` setStorageType(AsyncStorage)` in react native but it does not work. I've checked the index and it seems `setStorageType` isn't provided. Is there support for react native at the moment?

**Comment by bluebill1049** [comment]
we don't support react native right now.

**Comment by thebiltheory** [comment]
@jvalle-traxion `Session Storage` and `Local Storage`, which LST is based on, are [Web API's](https://developer.mozilla.org/en-US/docs/Web/API).
Hence not compatible with mobile devices.

Have a look at this: https://github.com/web-ridge/react-ridge-state
