### ISSUE TITLE
Typescript custom GlobalState type is not detected

### ISSUE THREAD

**Issue by sshquack** [bluebill1049/little-state-machine#77]
## Issue

Following the example at https://github.com/bluebill1049/little-state-machine#%EF%B8%8F-type-safety-ts does not override the `GlobalState`

Steps to repro:
1. Created custom typings file in `custom-types/global.d.ts`
2. Added custom typings file to the `tsconfig.json` using `typedRoots: ['./custom-typings']`
3. Added the `GlobalState` declaration

```
import 'little-state-machine';

declare module 'little-state-machine' {
  interface GlobalState {
    yourDetail: {
      name: string;
    };
  }
}
```
4. Typescript throws on action handler definition:
```
Property 'yourDetail' does not exist on type 'GlobalState'.  TS2339

     8 |   ...state,
     9 |   yourDetail: {
  > 10 |     ...state.yourDetail,
       |              ^
    11 |     ...payload,
    12 |   },
    13 | });
```

## Codesandbox

Please see issue at https://codesandbox.io/s/sad-lamarr-ko811?file=/src/App.tsx

**Comment by bluebill1049** [comment]
want to take a look at this example: https://codesandbox.io/s/typescript-forked-xs30h

**Comment by sshquack** [comment]
@bluebill1049 Thanks for the pointer. Moving the global.d.ts inside the src directory fixed the issue.

**Comment by sshquack** [comment]
@bluebill1049 Also thank you for creating amazing libraries like LSM and RHF. Love the quality of documentation, examples, and your attention to detail! ❤️ 🙏

**Comment by bluebill1049** [comment]
Thanks, @sshquack for the kind words! my pleasure to help!
