### ISSUE TITLE
Specify the type of state on hook

### ISSUE THREAD

**Issue by AuthorProxy** [bluebill1049/little-state-machine#90]
Make possible to create multiple stateMachines without creating GlobalState type, just infer it from updateAction first argument, or pass as generic to useStateMachine

**Comment by bluebill1049** [comment]
<img width="984" alt="Screen Shot 2021-06-16 at 8 50 00 am" src="https://user-images.githubusercontent.com/10513364/122133328-d682d900-ce7f-11eb-8aeb-f6b4fa043ff2.png">

take a look at this section above.

**Comment by AuthorProxy** [comment]
@bluebill1049 I want to use it like `useStateMachine<CustomPageState>` and use it on different pages with different types, you provide me to define one global state.

**Comment by snax4a** [comment]
I also would like to be able to pass state type as a generic to createStore method or useStateMachine or It would be great if state would be automatically infered.

It would provide us a better developer experience.
