### ISSUE TITLE
Way to test the store (E2E/Cypress)

### ISSUE THREAD

**Issue by ilicmarko** [bluebill1049/little-state-machine#92]
Is there an out of the box solution for testing the store out of the box?

A "common" practice for Redux is to attach the store to window and use it inside Cypress, example:

```js
if (window.Cypress) {
  window.store = store;
}
```

But in the case of little state machine `createStore` function doesn't return an instance that I can "hook" onto.

I guess I can check the storage, but that is a lot of work/logic inside a test, I would like to avoid it.

**Comment by bluebill1049** [comment]
You can access your session storage.

**Comment by ilicmarko** [comment]
I know, but that is async inside of Cypress, plus it required parsing the JSON. It adds complexity to the test that would be great if it can be avoided. Is there an option to expose the store instance in the future or some other way?

**Comment by bluebill1049** [comment]
> I know, but that is async inside of Cypress, plus it required parsing the JSON. It adds complexity to the test that would be great if it can be avoided. Is there an option to expose the store instance in the future or some other way?

not really.
