### ISSUE TITLE
crashes, when adding dev tool

### ISSUE THREAD

**Issue by Dujota** [bluebill1049/little-state-machine#93]
So as soon as i import the dev tool, app crashed with the below message. (state machine works just fine) 
I am using a Next.js app, any toughts or suggestions would really help :)  

```
\little-state-machine-devtools\dist\index.js:1
import * as React from 'react';
^^^^^^

SyntaxError: Cannot use import statement outside a module
```

the problem is with the import statement itself for some reason

`import { DevTool } from 'little-state-machine-devtools';`

**Comment by bluebill1049** [comment]
Can u reproduce this in a codesandbox or repo?

**Comment by Dujota** [comment]
@bluebill1049 i was able to fix the issue, it turns out, we were wrapping the statemachine inside a component which was using a provider/context (another npm package),

i had to move statemachine provider to the top of the tree in order for it no work properly with dev tools
