### ISSUE TITLE
Possibility to separate state to prevent rerendering?

### ISSUE THREAD

**Issue by KiwiKilian** [bluebill1049/little-state-machine#96]
I guess this is more a question or feature request: I would like to "subscribe" only to a part of the state to prevent unnecessary rerenders. For example `ComponentA` may only use `fieldA` of my global state. But currently if `fieldB` is changed also `ComponentA` is rerendered. Is there already any possibility to prevent this or could this be a future feature?

See [this csb](https://codesandbox.io/s/lsm-rerender-hogww) and watch the console for rerendering of the components.

**Comment by bluebill1049** [comment]
thanks for the suggestion, this lib is supposed to really simple and light. if you need to have a per component subscription model, you can consider lib such as zusland or jotai etc.
